const provincias = [
  { codigo: 'A', nombre: 'Salta' },
  { codigo: 'B', nombre: 'Provincia de Buenos Aires' },
  { codigo: 'C', nombre: 'Ciudad Autónoma de Buenos Aires' },
  { codigo: 'D', nombre: 'San Luis' },
  { codigo: 'E', nombre: 'Entre Ríos' },
  { codigo: 'F', nombre: 'La Rioja' },
  { codigo: 'G', nombre: 'Santiago del Estero' },
  { codigo: 'H', nombre: 'Chaco' },
  { codigo: 'J', nombre: 'San Juan' },
  { codigo: 'K', nombre: 'Catamarca' },
  { codigo: 'L', nombre: 'La Pampa' },
  { codigo: 'M', nombre: 'Mendoza' },
  { codigo: 'N', nombre: 'Misiones' },
  { codigo: 'P', nombre: 'Formosa' },
  { codigo: 'Q', nombre: 'Neuquén' },
  { codigo: 'R', nombre: 'Río Negro' },
  { codigo: 'S', nombre: 'Santa Fe' },
  { codigo: 'T', nombre: 'Tucumán' },
  { codigo: 'U', nombre: 'Chubut' },
  { codigo: 'V', nombre: 'Tierra del Fuego' },
  { codigo: 'W', nombre: 'Corrientes' },
  { codigo: 'X', nombre: 'Córdoba' },
  { codigo: 'Y', nombre: 'Jujuy' },
  { codigo: 'Z', nombre: 'Santa Cruz' },
];